services:
  # PostgreSQL Database
  - type: pserv
    name: xero-expense-db
    env: postgres
    plan: starter
    region: oregon
    ipAllowList: []

  # Backend Web Service
  - type: web
    name: xero-expense-api
    env: node
    plan: starter
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: xero-expense-db
          property: connectionString
      - key: XERO_CLIENT_ID
        sync: false
      - key: XERO_CLIENT_SECRET
        sync: false
      - key: XERO_REDIRECT_URI
        value: https://xero-expense-api.onrender.com/api/xero/callback
      - key: JWT_SECRET
        sync: false
      - key: OCR_API_KEY
        sync: false
      - key: OCR_API_URL
        value: https://api.ocr.space/parse/image
      - key: FRONTEND_URL
        value: https://xero-expense-app.onrender.com

  # Frontend Static Site
  - type: web
    name: xero-expense-app
    env: static
    plan: starter
    region: oregon
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://xero-expense-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
